# Generated by Django 6.0.5 on 2026-05-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_add_photo_positive_validators_and_comment_body_cleanup'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('pexels_id__gte', 1)), name='photos_pexels_id_positive'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('width__gte', 1)), name='photos_width_positive'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('height__gte', 1)), name='photos_height_positive'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(condition=models.Q(('photographer_id__gte', 1)), name='photos_photographer_id_positive'),
        ),
    ]
