# Generated by Django 6.0.5 on 2026-05-14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_add_photo_positive_check_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="composition_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DARK", "Dark & Moody"),
                    ("BRIGHT", "Bright & Airy"),
                    ("CONTRAST", "High Contrast"),
                    ("NEUTRAL", "Neutral"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.CheckConstraint(
                condition=models.Q(("composition_score__isnull", True), ("composition_score__gte", 1), _connector="OR"),
                name="photos_composition_score_min",
            ),
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.CheckConstraint(
                condition=models.Q(("composition_score__isnull", True), ("composition_score__lte", 10), _connector="OR"),
                name="photos_composition_score_max",
            ),
        ),
    ]
